apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-client-service
            port:
              number: {{ .Values.frontend.port }}
      - path: /goals
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-backend-service
            port:
              number: {{ .Values.backend.port }}
