kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
spec:
  storageClassName: {{ .Values.storageClassName.storage }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi