apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  {{- with .Values.backend }}
  {{- with .secrets }}
  password: {{ .password | b64enc }}
  username: {{ .username | b64enc }}
  {{- end }}
  {{- end }}

