apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  password: {{ .Values.backend.secrets.password | b64enc }}
  username: {{ .Values.backend.secrets.username | b64enc }}

