apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client-service
spec:
  selector:
    {{- include "frontend.Selectors" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: {{ .Values.service.type }} 

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  selector:
    {{- include "backend.Selectors" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: {{ .Values.service.type }} 