apiVersion: webapp.my.domain/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: myoperator
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-sample
spec:
  foo: "foobar"
  imageName: nginx
  replicas: 2
